import type { MenuItem, Modifier, InventoryItem } from "./types"

export const mockModifiers: Modifier[] = [
  {
    id: "size",
    name: "Size",
    type: "size",
    required: true,
    maxSelections: 1,
    options: [
      { id: "small", name: "Small", priceAdjustment: -0.5 },
      { id: "medium", name: "Medium", priceAdjustment: 0 },
      { id: "large", name: "Large", priceAdjustment: 0.75 },
    ],
  },
  {
    id: "milk",
    name: "Milk Type",
    type: "milk",
    required: false,
    maxSelections: 1,
    options: [
      { id: "whole", name: "Whole Milk", priceAdjustment: 0 },
      { id: "skim", name: "Skim Milk", priceAdjustment: 0 },
      { id: "oat", name: "Oat Milk", priceAdjustment: 0.6 },
      { id: "almond", name: "Almond Milk", priceAdjustment: 0.5 },
      { id: "soy", name: "Soy Milk", priceAdjustment: 0.5 },
    ],
  },
  {
    id: "syrup",
    name: "Syrup",
    type: "syrup",
    required: false,
    maxSelections: 3,
    options: [
      { id: "vanilla", name: "Vanilla", priceAdjustment: 0.5 },
      { id: "caramel", name: "Caramel", priceAdjustment: 0.5 },
      { id: "hazelnut", name: "Hazelnut", priceAdjustment: 0.5 },
      { id: "cinnamon", name: "Cinnamon", priceAdjustment: 0.5 },
    ],
  },
  {
    id: "extras",
    name: "Extras",
    type: "extra",
    required: false,
    maxSelections: 5,
    options: [
      { id: "extra-shot", name: "Extra Shot", priceAdjustment: 0.75 },
      { id: "decaf", name: "Decaf", priceAdjustment: 0 },
      { id: "extra-hot", name: "Extra Hot", priceAdjustment: 0 },
      { id: "whipped-cream", name: "Whipped Cream", priceAdjustment: 0.5 },
    ],
  },
]

export const mockMenuItems: MenuItem[] = [
  {
    id: "1",
    name: "Espresso",
    price: 2.5,
    category: "drinks",
    description: "Rich, bold espresso shot",
    modifiers: [mockModifiers[0], mockModifiers[3]],
    isFavorite: true,
  },
  {
    id: "2",
    name: "Cappuccino",
    price: 4.0,
    category: "drinks",
    description: "Espresso with steamed milk foam",
    modifiers: [mockModifiers[0], mockModifiers[1], mockModifiers[2], mockModifiers[3]],
    isFavorite: true,
  },
  {
    id: "3",
    name: "Latte",
    price: 4.5,
    category: "drinks",
    description: "Espresso with steamed milk",
    modifiers: [mockModifiers[0], mockModifiers[1], mockModifiers[2], mockModifiers[3]],
    isFavorite: true,
  },
  {
    id: "4",
    name: "Americano",
    price: 3.0,
    category: "drinks",
    description: "Espresso with hot water",
    modifiers: [mockModifiers[0], mockModifiers[3]],
  },
  {
    id: "5",
    name: "Croissant",
    price: 3.5,
    category: "food",
    description: "Buttery, flaky pastry",
    isFavorite: true,
  },
  {
    id: "6",
    name: "Bagel",
    price: 4.0,
    category: "food",
    description: "Fresh baked bagel with cream cheese",
  },
  {
    id: "7",
    name: "Muffin",
    price: 3.0,
    category: "pastries",
    description: "Fresh baked blueberry muffin",
  },
  {
    id: "8",
    name: "Cookie",
    price: 2.0,
    category: "pastries",
    description: "Chocolate chip cookie",
  },
]

export const mockInventoryItems: InventoryItem[] = [
  {
    id: "inv-1",
    menuItemId: "1",
    name: "Espresso Beans",
    currentStock: 25,
    minStock: 10,
    maxStock: 100,
    unit: "kg",
    costPerUnit: 15.5,
    supplier: "Premium Coffee Co.",
    lastRestocked: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    category: "ingredients",
  },
  {
    id: "inv-2",
    menuItemId: "2",
    name: "Milk",
    currentStock: 8,
    minStock: 15,
    maxStock: 50,
    unit: "liters",
    costPerUnit: 1.2,
    supplier: "Local Dairy Farm",
    lastRestocked: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    category: "ingredients",
  },
  {
    id: "inv-3",
    menuItemId: "3",
    name: "Oat Milk",
    currentStock: 3,
    minStock: 8,
    maxStock: 20,
    unit: "liters",
    costPerUnit: 2.8,
    supplier: "Oat Dreams Ltd.",
    lastRestocked: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    category: "ingredients",
  },
  {
    id: "inv-4",
    menuItemId: "5",
    name: "Croissants",
    currentStock: 12,
    minStock: 20,
    maxStock: 60,
    unit: "pieces",
    costPerUnit: 0.85,
    supplier: "French Bakery",
    lastRestocked: new Date(),
    category: "food",
  },
  {
    id: "inv-5",
    menuItemId: "6",
    name: "Bagels",
    currentStock: 18,
    minStock: 15,
    maxStock: 40,
    unit: "pieces",
    costPerUnit: 0.65,
    supplier: "Local Bakery",
    lastRestocked: new Date(),
    category: "food",
  },
  {
    id: "inv-6",
    menuItemId: "7",
    name: "Muffins",
    currentStock: 2,
    minStock: 12,
    maxStock: 30,
    unit: "pieces",
    costPerUnit: 1.2,
    supplier: "Sweet Treats Co.",
    lastRestocked: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    category: "pastries",
  },
  {
    id: "inv-7",
    menuItemId: "8",
    name: "Cookies",
    currentStock: 0,
    minStock: 24,
    maxStock: 60,
    unit: "pieces",
    costPerUnit: 0.45,
    supplier: "Cookie Factory",
    lastRestocked: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    category: "pastries",
  },
]
